version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ahosan
      MYSQL_DATABASE: ahosan
      MYSQL_USER: ahosan
      MYSQL_PASSWORD: ahosan
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysqlData:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - kafka-net

  zookeeper:
    image: wurstmeister/zookeeper
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-net
    depends_on:
      - zookeeper

  kafka-connect:
    image: debezium/connect:1.6
    container_name: kafka-connect
    volumes:
      - ./kafka-connect-mongodb:/kafka/plugins/kafka-connect-mongodb
      - ./dcmsql:/kafka/plugins/debezium-connector-mysql
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=connect-cluster
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - CONNECT_PLUGIN_PATH=/kafka/plugins
    depends_on:
      - kafka
      - zookeeper
      - mongo
    networks:
      - kafka-net

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-net

  mongo:
    image: mongo:latest
    container_name: contact_data_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: my_password
      MONGO_INITDB_DATABASE: contact_data
    ports:
      - "27017:27017"
    networks:
      - kafka-net

  contact_data_php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: contact_data_php
    volumes:
      - ../:/var/www/contact_data
    networks:
      - kafka-net

  nginx:
    image: nginx:latest
    container_name: contact_data_nginx
    volumes:
      - ../:/var/www/contact_data
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - contact_data_php
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
